/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package traveller.interfaz.panel;

import traveller.dominio.ISistema;

/**
 *
 * @author steffano
 */
public class PanelTipoEvento extends javax.swing.JPanel {

    private ISistema sistema;
    SubPanelNuevoTipoEvento nuevoTipo;
    SubPanelTipoEvento tipo;
    
    
    /**
     * Creates new form PanelTipoEvento
     */
    public PanelTipoEvento(ISistema miSistema) {
        initComponents();
        this.sistema = miSistema;
        nuevoTipo = new SubPanelNuevoTipoEvento(sistema);
        tipo = new SubPanelTipoEvento(sistema);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelTipoEvento = new javax.swing.JPanel();
        PanelBotones = new javax.swing.JPanel();
        panelContenedorTipoEvento = new javax.swing.JPanel();
        PanelSalidaDatosTipoEvento = new javax.swing.JPanel();
        PanelNuevaCiudad = new javax.swing.JPanel();
        CheckNuevoTipoEvento = new javax.swing.JCheckBox();
        lblNuevoTipoEvento = new javax.swing.JLabel();
        btnAgregarTipoEvento = new javax.swing.JButton();
        brnModificarTipoEvento = new javax.swing.JButton();
        btnBorrarTipoEvento = new javax.swing.JButton();

        PanelTipoEvento.setBackground(new java.awt.Color(230, 255, 245));

        PanelBotones.setBackground(new java.awt.Color(230, 255, 245));
        PanelBotones.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PanelBotonesFocusGained(evt);
            }
        });

        javax.swing.GroupLayout PanelBotonesLayout = new javax.swing.GroupLayout(PanelBotones);
        PanelBotones.setLayout(PanelBotonesLayout);
        PanelBotonesLayout.setHorizontalGroup(
            PanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 451, Short.MAX_VALUE)
        );
        PanelBotonesLayout.setVerticalGroup(
            PanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 377, Short.MAX_VALUE)
        );

        panelContenedorTipoEvento.setBackground(new java.awt.Color(230, 255, 245));

        javax.swing.GroupLayout PanelSalidaDatosTipoEventoLayout = new javax.swing.GroupLayout(PanelSalidaDatosTipoEvento);
        PanelSalidaDatosTipoEvento.setLayout(PanelSalidaDatosTipoEventoLayout);
        PanelSalidaDatosTipoEventoLayout.setHorizontalGroup(
            PanelSalidaDatosTipoEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PanelSalidaDatosTipoEventoLayout.setVerticalGroup(
            PanelSalidaDatosTipoEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 57, Short.MAX_VALUE)
        );

        PanelNuevaCiudad.setBackground(new java.awt.Color(180, 255, 245));

        CheckNuevoTipoEvento.setBackground(new java.awt.Color(180, 250, 245));
        CheckNuevoTipoEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckNuevoTipoEventoActionPerformed(evt);
            }
        });

        lblNuevoTipoEvento.setBackground(new java.awt.Color(153, 102, 51));
        lblNuevoTipoEvento.setText("Nuevo tipo de evento");

        javax.swing.GroupLayout PanelNuevaCiudadLayout = new javax.swing.GroupLayout(PanelNuevaCiudad);
        PanelNuevaCiudad.setLayout(PanelNuevaCiudadLayout);
        PanelNuevaCiudadLayout.setHorizontalGroup(
            PanelNuevaCiudadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNuevaCiudadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNuevoTipoEvento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CheckNuevoTipoEvento)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        PanelNuevaCiudadLayout.setVerticalGroup(
            PanelNuevaCiudadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNuevaCiudadLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelNuevaCiudadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNuevoTipoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckNuevoTipoEvento))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnAgregarTipoEvento.setBackground(new java.awt.Color(255, 77, 77));
        btnAgregarTipoEvento.setForeground(new java.awt.Color(50, 140, 50));
        btnAgregarTipoEvento.setText("Agregar");
        btnAgregarTipoEvento.setBorder(null);
        btnAgregarTipoEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarTipoEventoActionPerformed(evt);
            }
        });

        brnModificarTipoEvento.setBackground(new java.awt.Color(255, 77, 77));
        brnModificarTipoEvento.setForeground(new java.awt.Color(50, 140, 50));
        brnModificarTipoEvento.setText("Modificar");
        brnModificarTipoEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brnModificarTipoEventoActionPerformed(evt);
            }
        });

        btnBorrarTipoEvento.setBackground(new java.awt.Color(255, 77, 77));
        btnBorrarTipoEvento.setForeground(new java.awt.Color(50, 140, 50));
        btnBorrarTipoEvento.setText("Borrar");

        javax.swing.GroupLayout panelContenedorTipoEventoLayout = new javax.swing.GroupLayout(panelContenedorTipoEvento);
        panelContenedorTipoEvento.setLayout(panelContenedorTipoEventoLayout);
        panelContenedorTipoEventoLayout.setHorizontalGroup(
            panelContenedorTipoEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenedorTipoEventoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelContenedorTipoEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(brnModificarTipoEvento, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                    .addComponent(btnAgregarTipoEvento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBorrarTipoEvento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelSalidaDatosTipoEvento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelContenedorTipoEventoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PanelNuevaCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        panelContenedorTipoEventoLayout.setVerticalGroup(
            panelContenedorTipoEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenedorTipoEventoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelSalidaDatosTipoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelNuevaCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAgregarTipoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(brnModificarTipoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBorrarTipoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelTipoEventoLayout = new javax.swing.GroupLayout(PanelTipoEvento);
        PanelTipoEvento.setLayout(PanelTipoEventoLayout);
        PanelTipoEventoLayout.setHorizontalGroup(
            PanelTipoEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTipoEventoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTipoEventoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelContenedorTipoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112))
        );
        PanelTipoEventoLayout.setVerticalGroup(
            PanelTipoEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTipoEventoLayout.createSequentialGroup()
                .addComponent(panelContenedorTipoEvento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelTipoEvento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelTipoEvento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarTipoEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarTipoEventoActionPerformed
        // usar Metodos del contrato
    }//GEN-LAST:event_btnAgregarTipoEventoActionPerformed

    private void brnModificarTipoEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnModificarTipoEventoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brnModificarTipoEventoActionPerformed

    private void PanelBotonesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PanelBotonesFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_PanelBotonesFocusGained

    private void CheckNuevoTipoEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckNuevoTipoEventoActionPerformed
        boolean estaSeleccionado = CheckNuevoTipoEvento.isSelected();
        PanelSalidaDatosTipoEvento.removeAll();
        SubPanelNuevoTipoEvento tipoEvento = new SubPanelNuevoTipoEvento(sistema);
        tipoEvento.setBounds(0, 0, 439, 660);
        if (estaSeleccionado){
            nuevoTipo = new SubPanelNuevoTipoEvento(this.sistema);
            PanelSalidaDatosTipoEvento.add(nuevoTipo);
        }
        else{
            tipo = new SubPanelTipoEvento(this.sistema);
            PanelSalidaDatosTipoEvento.add(tipo);
        }
    }//GEN-LAST:event_CheckNuevoTipoEventoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckNuevoTipoEvento;
    private javax.swing.JPanel PanelBotones;
    private javax.swing.JPanel PanelNuevaCiudad;
    private javax.swing.JPanel PanelSalidaDatosTipoEvento;
    private javax.swing.JPanel PanelTipoEvento;
    private javax.swing.JButton brnModificarTipoEvento;
    private javax.swing.JButton btnAgregarTipoEvento;
    private javax.swing.JButton btnBorrarTipoEvento;
    private javax.swing.JLabel lblNuevoTipoEvento;
    private javax.swing.JPanel panelContenedorTipoEvento;
    // End of variables declaration//GEN-END:variables
}
