/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package traveller.interfaz.panel;

import traveller.dominio.ISistema;

/**
 *
 * @author steffano.britos
 */
public class PanelCiudades extends javax.swing.JPanel {
    private ISistema sistema;
    SubPanelNuevaCiudad nuevaCiudad;
    SubPanelCiudades ciudades = new SubPanelCiudades(this.sistema);
    /**
     * Creates new form PanelCiudades
     */
    public PanelCiudades(ISistema sistema) {
	initComponents();
	this.sistema = sistema;
	nuevaCiudad = new SubPanelNuevaCiudad(this.sistema);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        PanelCiudades = new javax.swing.JPanel();
        PanelSalidaDatos = new javax.swing.JPanel();
        PanelBotones = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        brnModificar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        PanelNuevaCiudad = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CheckNuevoUsuario = new javax.swing.JCheckBox();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        PanelCiudades.setBackground(new java.awt.Color(230, 255, 245));
        PanelCiudades.setBorder(new javax.swing.border.MatteBorder(null));
        PanelCiudades.setMinimumSize(new java.awt.Dimension(0, 0));

        javax.swing.GroupLayout PanelSalidaDatosLayout = new javax.swing.GroupLayout(PanelSalidaDatos);
        PanelSalidaDatos.setLayout(PanelSalidaDatosLayout);
        PanelSalidaDatosLayout.setHorizontalGroup(
            PanelSalidaDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 236, Short.MAX_VALUE)
        );
        PanelSalidaDatosLayout.setVerticalGroup(
            PanelSalidaDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );

        PanelBotones.setBackground(new java.awt.Color(230, 255, 245));
        PanelBotones.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PanelBotonesFocusGained(evt);
            }
        });

        btnAgregar.setBackground(new java.awt.Color(255, 77, 77));
        btnAgregar.setForeground(new java.awt.Color(50, 140, 50));
        btnAgregar.setText("Agregar");
        btnAgregar.setBorder(null);

        brnModificar.setBackground(new java.awt.Color(255, 77, 77));
        brnModificar.setForeground(new java.awt.Color(50, 140, 50));
        brnModificar.setText("Modificar");
        brnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brnModificarActionPerformed(evt);
            }
        });

        btnBorrar.setBackground(new java.awt.Color(255, 77, 77));
        btnBorrar.setForeground(new java.awt.Color(50, 140, 50));
        btnBorrar.setText("Borrar");

        javax.swing.GroupLayout PanelBotonesLayout = new javax.swing.GroupLayout(PanelBotones);
        PanelBotones.setLayout(PanelBotonesLayout);
        PanelBotonesLayout.setHorizontalGroup(
            PanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBotonesLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(PanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                    .addComponent(brnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        PanelBotonesLayout.setVerticalGroup(
            PanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(brnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelNuevaCiudad.setBackground(new java.awt.Color(180, 255, 245));

        jLabel1.setBackground(new java.awt.Color(153, 102, 51));
        jLabel1.setText("Ciudad nueva");

        CheckNuevoUsuario.setBackground(new java.awt.Color(180, 250, 245));
        CheckNuevoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckNuevoUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelNuevaCiudadLayout = new javax.swing.GroupLayout(PanelNuevaCiudad);
        PanelNuevaCiudad.setLayout(PanelNuevaCiudadLayout);
        PanelNuevaCiudadLayout.setHorizontalGroup(
            PanelNuevaCiudadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNuevaCiudadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CheckNuevoUsuario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelNuevaCiudadLayout.setVerticalGroup(
            PanelNuevaCiudadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelNuevaCiudadLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelNuevaCiudadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckNuevoUsuario))
                .addContainerGap())
        );

        javax.swing.GroupLayout PanelCiudadesLayout = new javax.swing.GroupLayout(PanelCiudades);
        PanelCiudades.setLayout(PanelCiudadesLayout);
        PanelCiudadesLayout.setHorizontalGroup(
            PanelCiudadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCiudadesLayout.createSequentialGroup()
                .addGroup(PanelCiudadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PanelSalidaDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelCiudadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelCiudadesLayout.createSequentialGroup()
                            .addGap(75, 75, 75)
                            .addComponent(PanelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(PanelCiudadesLayout.createSequentialGroup()
                            .addGap(152, 152, 152)
                            .addComponent(PanelNuevaCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        PanelCiudadesLayout.setVerticalGroup(
            PanelCiudadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCiudadesLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(PanelSalidaDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelNuevaCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelCiudades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelCiudades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void brnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brnModificarActionPerformed

    private void PanelBotonesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PanelBotonesFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_PanelBotonesFocusGained

    private void CheckNuevoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckNuevoUsuarioActionPerformed
        boolean estaSeleccionado = CheckNuevoUsuario.isSelected();
        PanelSalidaDatos.removeAll();
        nuevaCiudad.setBounds(0, 0, 439, 660);
        if (estaSeleccionado){
            nuevaCiudad = new SubPanelNuevaCiudad(this.sistema);
            PanelSalidaDatos.add(nuevaCiudad);
        }
        else{
            ciudades = new SubPanelCiudades(this.sistema);
            PanelSalidaDatos.add(ciudades);
        }
    }//GEN-LAST:event_CheckNuevoUsuarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckNuevoUsuario;
    private javax.swing.JPanel PanelBotones;
    private javax.swing.JPanel PanelCiudades;
    private javax.swing.JPanel PanelNuevaCiudad;
    private javax.swing.JPanel PanelSalidaDatos;
    private javax.swing.JButton brnModificar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
