package traveller.interfaz.panel;

import java.util.ArrayList;
import javax.swing.ButtonGroup;
import javax.swing.ButtonModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import traveller.dominio.ISistema;
import traveller.dominio.TipoEvento;

/**
 *
 * @author steffano
 */
public class PanelTipoEvento extends javax.swing.JPanel {

    private ISistema sistema;
    SubPanelNuevoTipoEvento nuevoTipo;
    SubPanelTipoEvento tipo;
    
    
    /**
     * Creates new form PanelTipoEvento
     */
    public PanelTipoEvento(ISistema miSistema) {
        initComponents();
        this.sistema = miSistema;
        ArrayList<String> nombresTiposEventos = this.sistema.getNombresTiposEventos();
        comboTipos.setModel(new DefaultComboBoxModel(nombresTiposEventos.toArray()));
        //nuevoTipo = new SubPanelNuevoTipoEvento(sistema);
        //tipo = new SubPanelTipoEvento(sistema);
        ButtonGroup btnGrupoTiposEventos = new ButtonGroup();
        btnGrupoTiposEventos.add(radioAgregarTipoEvento);
        btnGrupoTiposEventos.add(radioModificarTipoEvento);
        btnGrupoTiposEventos.add(radioBorrarTipoEvento);
        ButtonModel seleccion = btnGrupoTiposEventos.getSelection();
        
        //String nombreTipoEvento = txtNuevoTipoEvento.getText().toUpperCase();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelTipoEvento = new javax.swing.JPanel();
        PanelBotones = new javax.swing.JPanel();
        panelContenedorTipoEvento = new javax.swing.JPanel();
        radioAgregarTipoEvento = new javax.swing.JRadioButton();
        radioModificarTipoEvento = new javax.swing.JRadioButton();
        radioBorrarTipoEvento = new javax.swing.JRadioButton();
        txtNuevoTipoEvento = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        comboTipos = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        PanelTipoEvento.setBackground(new java.awt.Color(230, 255, 245));

        PanelBotones.setBackground(new java.awt.Color(230, 255, 245));
        PanelBotones.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PanelBotonesFocusGained(evt);
            }
        });

        panelContenedorTipoEvento.setBackground(new java.awt.Color(230, 255, 245));

        radioAgregarTipoEvento.setText("Agregar");
        radioAgregarTipoEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioAgregarTipoEventoActionPerformed(evt);
            }
        });

        radioModificarTipoEvento.setText("Modificar");
        radioModificarTipoEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioModificarTipoEventoActionPerformed(evt);
            }
        });

        radioBorrarTipoEvento.setText("Borrar");
        radioBorrarTipoEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBorrarTipoEventoActionPerformed(evt);
            }
        });

        txtNuevoTipoEvento.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setText("Tipo Evento");

        comboTipos.setBackground(new java.awt.Color(230, 138, 0));
        comboTipos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboTipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTiposActionPerformed(evt);
            }
        });

        jButton1.setText("Enviar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelContenedorTipoEventoLayout = new javax.swing.GroupLayout(panelContenedorTipoEvento);
        panelContenedorTipoEvento.setLayout(panelContenedorTipoEventoLayout);
        panelContenedorTipoEventoLayout.setHorizontalGroup(
            panelContenedorTipoEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenedorTipoEventoLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(txtNuevoTipoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelContenedorTipoEventoLayout.createSequentialGroup()
                .addGroup(panelContenedorTipoEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelContenedorTipoEventoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelContenedorTipoEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelContenedorTipoEventoLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(radioAgregarTipoEvento)
                            .addGap(23, 23, 23)
                            .addComponent(radioModificarTipoEvento)
                            .addGap(18, 18, 18)
                            .addComponent(radioBorrarTipoEvento))
                        .addGroup(panelContenedorTipoEventoLayout.createSequentialGroup()
                            .addGap(65, 65, 65)
                            .addGroup(panelContenedorTipoEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(comboTipos, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        panelContenedorTipoEventoLayout.setVerticalGroup(
            panelContenedorTipoEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenedorTipoEventoLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(comboTipos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNuevoTipoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(panelContenedorTipoEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioAgregarTipoEvento)
                    .addComponent(radioModificarTipoEvento)
                    .addComponent(radioBorrarTipoEvento))
                .addGap(63, 63, 63)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel2.setBackground(new java.awt.Color(255, 204, 255));
        jLabel2.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Administración de tipos de eventos");

        javax.swing.GroupLayout PanelBotonesLayout = new javax.swing.GroupLayout(PanelBotones);
        PanelBotones.setLayout(PanelBotonesLayout);
        PanelBotonesLayout.setHorizontalGroup(
            PanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBotonesLayout.createSequentialGroup()
                .addComponent(panelContenedorTipoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 93, Short.MAX_VALUE))
            .addGroup(PanelBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelBotonesLayout.setVerticalGroup(
            PanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBotonesLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelContenedorTipoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(277, Short.MAX_VALUE))
        );

        PanelTipoEvento.add(PanelBotones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelTipoEvento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelTipoEvento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void PanelBotonesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PanelBotonesFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_PanelBotonesFocusGained

    private void comboTiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTiposActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboTiposActionPerformed

    private void radioBorrarTipoEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBorrarTipoEventoActionPerformed
        txtNuevoTipoEvento.setEnabled(false);
        comboTipos.setEnabled(true);
    }//GEN-LAST:event_radioBorrarTipoEventoActionPerformed

    private void radioModificarTipoEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioModificarTipoEventoActionPerformed
        txtNuevoTipoEvento.setEnabled(true);
        comboTipos.setEnabled(true);
    }//GEN-LAST:event_radioModificarTipoEventoActionPerformed

    private void radioAgregarTipoEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioAgregarTipoEventoActionPerformed
        txtNuevoTipoEvento.setEnabled(true);
        comboTipos.setEnabled(false);
    }//GEN-LAST:event_radioAgregarTipoEventoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ButtonGroup btnGrupoTipoEventos = new ButtonGroup();
        btnGrupoTipoEventos.add(radioAgregarTipoEvento);
        btnGrupoTipoEventos.add(radioModificarTipoEvento);
        btnGrupoTipoEventos.add(radioBorrarTipoEvento);
        ButtonModel seleccion = btnGrupoTipoEventos.getSelection();
        String unNombreTipoEvento = txtNuevoTipoEvento.getText().toUpperCase();
        int posicion = comboTipos.getSelectedIndex();
        TipoEvento tipoEvento = new TipoEvento(unNombreTipoEvento);
        if (seleccion == radioAgregarTipoEvento.getModel()) {
            if(this.sistema.altaTipoEvento(tipoEvento)){
                JOptionPane.showMessageDialog(PanelBotones, "Registro exitoso.", "AVISO", JOptionPane.WARNING_MESSAGE);
                System.out.println("Registrado");
            }
            else{
                JOptionPane.showMessageDialog(PanelBotones, "No se efectuó el registro.", "AVISO", JOptionPane.WARNING_MESSAGE);
                System.out.println("NO Registrado");
            }
        }
        if (seleccion == radioModificarTipoEvento.getModel()) {
            this.sistema.modificarTipoEvento(unNombreTipoEvento, posicion);
        }
        if (seleccion == radioBorrarTipoEvento.getModel()) {
            int posABorrar = comboTipos.getSelectedIndex();
           TipoEvento tipoEventoABorrar = this.sistema.obtenerTipoEvento(posABorrar);
            this.sistema.bajaTipoEvento(tipoEventoABorrar);
        }
        txtNuevoTipoEvento.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelBotones;
    private javax.swing.JPanel PanelTipoEvento;
    private javax.swing.JComboBox<String> comboTipos;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel panelContenedorTipoEvento;
    private javax.swing.JRadioButton radioAgregarTipoEvento;
    private javax.swing.JRadioButton radioBorrarTipoEvento;
    private javax.swing.JRadioButton radioModificarTipoEvento;
    private javax.swing.JTextField txtNuevoTipoEvento;
    // End of variables declaration//GEN-END:variables
}
