package traveller.interfaz.panel;

import javax.swing.ButtonGroup;
import javax.swing.ButtonModel;
import traveller.dominio.ISistema;
import traveller.dominio.TipoEvento;

/**
 *
 * @author steffano
 */
public class PanelTipoEvento extends javax.swing.JPanel {

    private ISistema sistema;
    SubPanelNuevoTipoEvento nuevoTipo;
    SubPanelTipoEvento tipo;
    
    
    /**
     * Creates new form PanelTipoEvento
     */
    public PanelTipoEvento(ISistema miSistema) {
        initComponents();
        this.sistema = miSistema;
        //nuevoTipo = new SubPanelNuevoTipoEvento(sistema);
        //tipo = new SubPanelTipoEvento(sistema);
        ButtonGroup btnGrupoTiposEventos = new ButtonGroup();
        btnGrupoTiposEventos.add(radioAgregarTipoEvento);
        btnGrupoTiposEventos.add(radioModificarTipoEvento);
        btnGrupoTiposEventos.add(radioBorrarTipoEvento);
        ButtonModel seleccion = btnGrupoTiposEventos.getSelection();
        int posicion = comboTipos.getSelectedIndex();
        String nombreTipoEvento = txtNuevoTipoEvento.getText().toUpperCase();
        
        TipoEvento tipoEvento = new TipoEvento(nombreTipoEvento);
        if (seleccion == radioAgregarTipoEvento.getModel()) {
            this.sistema.altaTipoEvento(tipoEvento);
        }
        if (seleccion == radioModificarTipoEvento.getModel()) {
            this.sistema.modificarTipoEvento(nombreTipoEvento, posicion);
        }
        if (seleccion == radioBorrarTipoEvento.getModel()) {
            int posABorrar = comboTipos.getSelectedIndex();
           TipoEvento tipoEventoABorrar = this.sistema.obtenerTipoEvento(posABorrar);
            this.sistema.bajaTipoEvento(tipoEventoABorrar);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelTipoEvento = new javax.swing.JPanel();
        PanelBotones = new javax.swing.JPanel();
        panelContenedorTipoEvento = new javax.swing.JPanel();
        radioAgregarTipoEvento = new javax.swing.JRadioButton();
        radioModificarTipoEvento = new javax.swing.JRadioButton();
        radioBorrarTipoEvento = new javax.swing.JRadioButton();
        txtNuevoTipoEvento = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        comboTipos = new javax.swing.JComboBox();

        PanelTipoEvento.setBackground(new java.awt.Color(230, 255, 245));

        PanelBotones.setBackground(new java.awt.Color(230, 255, 245));
        PanelBotones.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PanelBotonesFocusGained(evt);
            }
        });

        javax.swing.GroupLayout PanelBotonesLayout = new javax.swing.GroupLayout(PanelBotones);
        PanelBotones.setLayout(PanelBotonesLayout);
        PanelBotonesLayout.setHorizontalGroup(
            PanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 451, Short.MAX_VALUE)
        );
        PanelBotonesLayout.setVerticalGroup(
            PanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 377, Short.MAX_VALUE)
        );

        panelContenedorTipoEvento.setBackground(new java.awt.Color(230, 255, 245));

        radioAgregarTipoEvento.setText("Agregar");

        radioModificarTipoEvento.setText("Modificar");

        radioBorrarTipoEvento.setText("Borrar");

        txtNuevoTipoEvento.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setText("Tipo Evento");

        comboTipos.setBackground(new java.awt.Color(230, 138, 0));
        comboTipos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboTipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTiposActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelContenedorTipoEventoLayout = new javax.swing.GroupLayout(panelContenedorTipoEvento);
        panelContenedorTipoEvento.setLayout(panelContenedorTipoEventoLayout);
        panelContenedorTipoEventoLayout.setHorizontalGroup(
            panelContenedorTipoEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenedorTipoEventoLayout.createSequentialGroup()
                .addGroup(panelContenedorTipoEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelContenedorTipoEventoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(radioAgregarTipoEvento)
                        .addGap(23, 23, 23)
                        .addComponent(radioModificarTipoEvento)
                        .addGap(18, 18, 18)
                        .addComponent(radioBorrarTipoEvento))
                    .addGroup(panelContenedorTipoEventoLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(panelContenedorTipoEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(comboTipos, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(88, Short.MAX_VALUE))
            .addGroup(panelContenedorTipoEventoLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(txtNuevoTipoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelContenedorTipoEventoLayout.setVerticalGroup(
            panelContenedorTipoEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenedorTipoEventoLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(comboTipos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNuevoTipoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(panelContenedorTipoEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioAgregarTipoEvento)
                    .addComponent(radioModificarTipoEvento)
                    .addComponent(radioBorrarTipoEvento))
                .addGap(88, 88, 88))
        );

        javax.swing.GroupLayout PanelTipoEventoLayout = new javax.swing.GroupLayout(PanelTipoEvento);
        PanelTipoEvento.setLayout(PanelTipoEventoLayout);
        PanelTipoEventoLayout.setHorizontalGroup(
            PanelTipoEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTipoEventoLayout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(PanelTipoEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelContenedorTipoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        PanelTipoEventoLayout.setVerticalGroup(
            PanelTipoEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTipoEventoLayout.createSequentialGroup()
                .addComponent(panelContenedorTipoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(PanelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelTipoEvento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelTipoEvento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void PanelBotonesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PanelBotonesFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_PanelBotonesFocusGained

    private void comboTiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTiposActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboTiposActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelBotones;
    private javax.swing.JPanel PanelTipoEvento;
    private javax.swing.JComboBox<String> comboTipos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panelContenedorTipoEvento;
    private javax.swing.JRadioButton radioAgregarTipoEvento;
    private javax.swing.JRadioButton radioBorrarTipoEvento;
    private javax.swing.JRadioButton radioModificarTipoEvento;
    private javax.swing.JTextField txtNuevoTipoEvento;
    // End of variables declaration//GEN-END:variables
}
