/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package traveller.interfaz.panel;

import java.awt.Dialog;
import java.awt.Rectangle;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.ArrayList;
import javax.swing.ButtonGroup;
import javax.swing.ButtonModel;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import traveller.dominio.Ciudad;
import traveller.dominio.ISistema;

/**
 *
 * @author steffano.britos
 */
public class PanelCiudades extends javax.swing.JPanel {

    private ISistema sistema;
    SubPanelNuevaCiudad nuevaCiudad;
    SubPanelCiudades ciudades;
    boolean estaSeleccionado;

    /**
     * Creates new form PanelCiudades
     */
    public PanelCiudades(final ISistema sistema) {
        initComponents();
        this.sistema = sistema;
        ArrayList<String> nombresCiudades = this.sistema.getNombresCiudades();
        comboUsuarios.setModel(new DefaultComboBoxModel(nombresCiudades.toArray()));
        comboUsuarios.setSelectedIndex(0);
        //Visivilidad
        jPanel1.setVisible(false);
        jPanel3.setVisible(true);
        btnAplicar.setEnabled(false);
        //brnModificarCiudad.setEnabled(true);
        //btnBorrarCiudad.setEnabled(true);

        btnAplicar.setEnabled(false);

        //grupo.addItemListener(new ItemListener() {
        /*@Override
            public void itemStateChanged(ItemEvent e) {
                //PanelDatosCiudad.removeAll();
                if (grupoCiudd.isSelected()) {
                    
                    jPanel1.setVisible(true);
                    jPanel3.setVisible(false);
                    PanelCiudades.repaint();
                    btnAplicar.setEnabled(true);
                   
                } else {
                    jPanel3.setVisible(true);
                    jPanel1.setVisible(false);
                    PanelCiudades.repaint();
                    btnAplicar.setEnabled(false);
                   
                }
            }*/
        //});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        PanelCiudades = new javax.swing.JPanel();
        PanelBotones = new javax.swing.JPanel();
        btnAplicar = new javax.swing.JButton();
        radioAgregar = new javax.swing.JRadioButton();
        radioModificar = new javax.swing.JRadioButton();
        radioBorrar = new javax.swing.JRadioButton();
        PanelDatosCiudad = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblNuevaCiudad = new javax.swing.JLabel();
        txtNuevoUsuario = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        comboUsuarios = new javax.swing.JComboBox();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        PanelCiudades.setBackground(new java.awt.Color(230, 255, 245));
        PanelCiudades.setBorder(new javax.swing.border.MatteBorder(null));
        PanelCiudades.setMinimumSize(new java.awt.Dimension(0, 0));
        PanelCiudades.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelBotones.setBackground(new java.awt.Color(230, 255, 245));
        PanelBotones.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PanelBotonesFocusGained(evt);
            }
        });

        btnAplicar.setBackground(new java.awt.Color(255, 77, 77));
        btnAplicar.setForeground(new java.awt.Color(50, 140, 50));
        btnAplicar.setText("Aplicar");
        btnAplicar.setBorder(null);
        btnAplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAplicarActionPerformed(evt);
            }
        });

        radioAgregar.setText("Agregar");
        radioAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioAgregarActionPerformed(evt);
            }
        });

        radioModificar.setText("Modificar");
        radioModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioModificarActionPerformed(evt);
            }
        });

        radioBorrar.setText("Borrar");
        radioBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelBotonesLayout = new javax.swing.GroupLayout(PanelBotones);
        PanelBotones.setLayout(PanelBotonesLayout);
        PanelBotonesLayout.setHorizontalGroup(
            PanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBotonesLayout.createSequentialGroup()
                .addGroup(PanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelBotonesLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(radioAgregar)
                        .addGap(18, 18, 18)
                        .addComponent(radioModificar)
                        .addGap(18, 18, 18)
                        .addComponent(radioBorrar))
                    .addGroup(PanelBotonesLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(btnAplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        PanelBotonesLayout.setVerticalGroup(
            PanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioAgregar)
                    .addComponent(radioModificar)
                    .addComponent(radioBorrar))
                .addGap(18, 18, 18)
                .addComponent(btnAplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        PanelCiudades.add(PanelBotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        PanelDatosCiudad.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        lblNuevaCiudad.setText("Nombre ciudad");

        txtNuevoUsuario.setBackground(new java.awt.Color(177, 174, 255));
        txtNuevoUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNuevaCiudad)
                    .addComponent(txtNuevoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(166, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNuevaCiudad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNuevoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        PanelDatosCiudad.add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));

        comboUsuarios.setBackground(new java.awt.Color(230, 138, 0));
        comboUsuarios.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboUsuariosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(comboUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(106, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(comboUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        PanelDatosCiudad.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        PanelCiudades.add(PanelDatosCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 12, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelCiudades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelCiudades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void PanelBotonesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PanelBotonesFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_PanelBotonesFocusGained

    private void btnAplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAplicarActionPerformed
        ButtonGroup btnGrupoCiudades = new ButtonGroup();
        btnGrupoCiudades.add(radioAgregar);
        btnGrupoCiudades.add(radioModificar);
        btnGrupoCiudades.add(radioBorrar);
        ButtonModel seleccion = btnGrupoCiudades.getSelection();
        int posicion = comboUsuarios.getSelectedIndex();
        String nombreCiudad = txtNuevoUsuario.getText().toUpperCase();
        Ciudad unaCiudad = new Ciudad(nombreCiudad);
        if (seleccion == radioAgregar.getModel()) {
            this.sistema.altaCiudad(unaCiudad);
        }
        if (seleccion == radioModificar.getModel()) {
            this.sistema.modificarCiudad(nombreCiudad, posicion);
        }
        if (seleccion == radioBorrar.getModel()) {
            this.sistema.bajaCiudad(unaCiudad);
        }
        
    }//GEN-LAST:event_btnAplicarActionPerformed

    private void comboUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboUsuariosActionPerformed

    private void radioAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioAgregarActionPerformed
        jPanel1.setVisible(true);
        jPanel3.setVisible(false);
        btnAplicar.setEnabled(true);
        //btnAplicar.setEnabled(false);
    }//GEN-LAST:event_radioAgregarActionPerformed

    private void radioModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioModificarActionPerformed
        jPanel1.setVisible(true);
        jPanel3.setVisible(true);
        btnAplicar.setEnabled(true);
    }//GEN-LAST:event_radioModificarActionPerformed

    private void radioBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBorrarActionPerformed
        jPanel1.setVisible(false);
        jPanel3.setVisible(true);
        btnAplicar.setEnabled(true);
    }//GEN-LAST:event_radioBorrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelBotones;
    private javax.swing.JPanel PanelCiudades;
    private javax.swing.JPanel PanelDatosCiudad;
    private javax.swing.JButton btnAplicar;
    private javax.swing.JComboBox<String> comboUsuarios;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblNuevaCiudad;
    private javax.swing.JRadioButton radioAgregar;
    private javax.swing.JRadioButton radioBorrar;
    private javax.swing.JRadioButton radioModificar;
    private javax.swing.JTextField txtNuevoUsuario;
    // End of variables declaration//GEN-END:variables
}
