/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package traveller.interfaz.panel;

import traveller.dominio.ISistema;

/**
 *
 * @author steffano
 */
public class SubPanelNuevaCiudad extends javax.swing.JPanel {

    ISistema sistema;
    
    /**
     * Creates new form SubPanelNuevoUsuario
     */
    public SubPanelNuevaCiudad(ISistema miSistema) {
        initComponents();
        this.sistema = miSistema;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelNuevoUsuario = new javax.swing.JPanel();
        lblNuevoUsuario = new javax.swing.JLabel();
        txtNuevoUsuario = new javax.swing.JTextField();

        PanelNuevoUsuario.setBackground(new java.awt.Color(179, 179, 255));

        lblNuevoUsuario.setText("Nueva ciudad");

        txtNuevoUsuario.setBackground(new java.awt.Color(177, 174, 255));
        txtNuevoUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNuevoUsuario.setText("ingrese ciudad");

        javax.swing.GroupLayout PanelNuevoUsuarioLayout = new javax.swing.GroupLayout(PanelNuevoUsuario);
        PanelNuevoUsuario.setLayout(PanelNuevoUsuarioLayout);
        PanelNuevoUsuarioLayout.setHorizontalGroup(
            PanelNuevoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNuevoUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNuevoUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNuevoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );
        PanelNuevoUsuarioLayout.setVerticalGroup(
            PanelNuevoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNuevoUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelNuevoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNuevoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNuevoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelNuevoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelNuevoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelNuevoUsuario;
    private javax.swing.JLabel lblNuevoUsuario;
    private javax.swing.JTextField txtNuevoUsuario;
    // End of variables declaration//GEN-END:variables
}
